apiVersion: 1

datasources:
  - name: Telemetry
    type: postgres
    uid: telemetry-pg
    access: proxy
    url: postgres:5432
    user: telemetry
    secureJsonData:
      password: "telemetry"
    jsonData:
      database: telemetry
      sslmode: "disable"
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
    isDefault: false
    editable: true
